### ISSUE TITLE
It would be a wonderful addition to the language, but it's homely.

### ISSUE THREAD

**Issue by kizerkizer** [tc39/proposal-pipeline-operator#138]
Why not **~>** instead of **|>** ? 

or -> or ~: or |-> or |~> or |=> ?

**Comment by kizerkizer** [comment]
No reason we can't be different? It's ugly!

~> is the way to go.

**Comment by ljharb** [comment]
That looks too similar to the bitwise ~ operator, i suspect.

**Comment by kizerkizer** [comment]
> Every example of prior art [listed in the readme](https://github.com/tc39/proposal-pipeline-operator#esnext-proposal-the-pipeline-operator) uses `|>`.

What does it matter what symbol others have used? The feature is obviously the same. |> is ugly and hard to type. ~> is very fun to type.

**Comment by charmander** [comment]
> Why not `~>` instead of `|>` ?

it looks worse and `~` is hard to type on some keyboard layouts

> or `->`

it looks like an arrow function

> or `~:`

that’s just two random symbols

> or `|->` or `|~>` or `|=>` ?

they look much worse.

**Comment by aboyton** [comment]
`~>` to me makes me think that it’s a variation of `->` (that is it’s some sort of dereference—`(*a).b` for those with a C background or even PHP).

The pipe operator is just that, a pipe just like in your command line (except you can’t use `|` as that’s bit wise OR and so an arrow makes it look like a chained pipe).

**Comment by topaxi** [comment]
@kizerkizer it might be fun to type on your keyboard, but to type `~` on my keyboard I'd have to press a modifier and another key two times, `|` is one modifier and `1`.

**Comment by igabesz** [comment]
Don't forget the fancy ligatures, the current syntax `|>` looks badass IMHO. Fira Code, Monokai theme, unknown syntax 😢

![image](https://user-images.githubusercontent.com/3373181/46528014-ff5f0d80-c892-11e8-9e72-75f3184207d5.png)

**Comment by jrista** [comment]
> Why not **~>** instead of **|>** ?

Aside from |> being prior art, used in all the existing pipe operators I know if...it looks DAMN SEXY when you use a font with ligatures!

![ligature-pipes](https://user-images.githubusercontent.com/238441/62816893-4c32f680-baeb-11e9-8958-bbe75c6a2b7d.png)

**Comment by tabatkins** [comment]
Closing this issue, as the proposal has advanced to stage 2 with Hack-style syntax.

(And I agree, I use a coding font with a `|>` ligature just like the above comment's, and it looks *nice*.)
