### ISSUE TITLE
pipe like template strings or thenable

### ISSUE THREAD

**Issue by EduardoRFS** [tc39/proposal-pipeline-operator#141]
I was thinking about how template strings can have custom behavior, what if instead of having a "holy grail" of pipe operator, we create a way to customize it, and by default being only the simplest non-async operations, being hack-able it's one of the reasons of why promises and generators are so flexible.

Having some property on the first function set to true, or on the first value set to a function, force it to instead of part of the chain, being the pipe function, we can use something like ```Symbol('pipeline')```, and it allows basically all expression statements by default

Both options solve basically all problems without making it complex and without making ugly syntax

```javascript
const { pipeP } = require('ramda')

const promise = Promise.resolve(1)
promise[Symbol('pipeline')] = pipeP

promise
|> double // return a Promise<2>
|> createFetch() // create the fetch(before the chain) and call fetch(2)
|> console.log // log the result of fetch(2)

//or

const { pipeP } = require('ramda')
pipeP[Symbol('pipeline')] = true;

const promise = Promise.resolve(1)

promise
|> pipeP // called pipeP(double, createFetch(), console.log)(promise)
|> double // return a Promise<2>
|> createFetch() // create the fetch(before the chain) and call fetch(2)
|> console.log // log the result of fetch(2)

```

**Comment by tabatkins** [comment]
Closing this issue, as the proposal has advanced to stage 2 with Hack-style syntax.

(And in general, operator overloading is a fraught topic with a lot of thorny issues. We might address it someday, but not as a one-off for this proposal.)
