### ISSUE TITLE
[question]: Progress on deciding operator precedence

### ISSUE THREAD

**Issue by KilianKilmister** [tc39/proposal-pipeline-operator#172]
I'm working on a JS/ES like shell grammar for commandline use. and for that, a Pipeline Operator is obviously a must. and since i would like to use the same operator precedences as JS to make usage easier for js programmers, i wan't to consider what this proposal states precedence should be.

In the proposal it stated: 

> The precedence of |> sits between the ternary operator and ||. It is left-associative. [bug](#23)

But the linked discussion hasn't come to any conclusion. Has there been any progress on that so far?

I commented my opinion in [#23](https://github.com/tc39/proposal-pipeline-operator/issues/23#issuecomment-687102637)

**Comment by tabatkins** [comment]
Closing this issue, as the proposal has advanced to stage 2 with Hack-style syntax. (The precedence of `|>` is the same as `=>`.)
