### ISSUE TITLE
Possible ambiguity when tuples and smart placeholder are used together

### ISSUE THREAD

**Issue by ducaale** [tc39/proposal-pipeline-operator#176]
Currently, smart pipelines use the hash symbol for placeholders
```js
['hello', 'world'] |> #.concat(#[0]);
// ['hello', 'world', 'hello']
```

But with the [record & tuple proposal](https://github.com/tc39/proposal-record-tuple) which is currently in stage 2, the hash symbol is also used for creating tuples and records. This means a user might expect a different result in the above example:

```js
['hello', 'world'] |> #.concat(#[0]);
// ['hello', 'world', #[0]]
```

**Comment by tabatkins** [comment]
This was a valid issue, and caused us to switch away from `#` as the placeholder; we're currently using `^`, but see #91 for further bikeshedding. Closing, since this issue is resolved now.
