### ISSUE TITLE
may i pipe a tuple?

### ISSUE THREAD

**Issue by xp44mm** [tc39/proposal-pipeline-operator#196]
just like this:
```js
[a,b,c,...]
||> func
```
compile to:

```js
func(...[a,b,c,...])
```

**Comment by ljharb** [comment]
Using the stage 2 (Hack) syntax:
```js
anyIterable // array, tuple, whatever
  |> func(...^)
```

**Comment by xp44mm** [comment]
@Alhadis thank you!
```js
args
|> args => func(...args)
```
can do this too!

**Comment by Alhadis** [comment]
@xp44mm … I think you meant to tag somebody else, because I don't think either of us have met before…

**Comment by xp44mm** [comment]
@Alhadis Yes, I'd like to at that be upstairs @ljharb, but Smart Tip let me choose you by mistake.

**Comment by ljharb** [comment]
You can’t do your second example, because the stage 2 proposal uses hack pipes. Every section in a pipe needs to use the placeholder.

**Comment by tabatkins** [comment]
It looks like @ljharb fully answered the question, so I'll go ahead and close this issue. Thanks!
