### ISSUE TITLE
Are you allowed to use the topic binding in a function body?

### ISSUE THREAD

**Issue by noppa** [tc39/proposal-pipeline-operator#197]
Is the following valid use of the topic placeholder?
```javascript
x |> setTimeout(() => console.log(^))
```
From my understanding of the spec, it is, but I wanted to make sure because there's no explicit example of this pattern in the examples.

**Comment by mAAdhaTTah** [comment]
Yes, that's valid, and it would close over the topic value at that step in the pipeline.
