### ISSUE TITLE
Isn't the bind operator similar?

### ISSUE THREAD

**Issue by spion** [tc39/proposal-pipeline-operator#2]
Page: https://github.com/zenparsing/es-function-bind

Works with the `this` argument instead of the first argument

An extra nice property is that it allows creating bound functions

**Comment by mindeavor** [comment]
It's similar, but my main problem with the bind operator is that it requires the use of the keyword `this` to do function chaining. Previous conversations here: https://esdiscuss.org/topic/the-pipeline-operator-making-multiple-function-calls-look-great#content-3

**Comment by spion** [comment]
`this` isn't *really* a keyword, it is the natural default argument in JavaScript. The reason why it hasn't been used in that way is the lack of syntax to do it, which is precisely what `::` would solve.

**Comment by bergus** [comment]
> main problem with the bind operator is that it requires the use of the keyword `this` to do function chaining

I'd have said "it **allows** us to use the `this` keyword with function chaining". My argument is that JS has always been an object-oriented language, and using the `this` keyword would close the gap between methods and functions even more. Those custom pipeline-able functions from your examples would hardly look different, only they'd get even more concise without needing to declare the implicit argument.

**Comment by mindeavor** [comment]
@bergus I would argue JS has always intended to *look like* an object-oriented language, but I think I would be getting off topic at that point :)

In any case, you make a good point. As you said, the current examples would not look much different with the bind operator (I do consider the implicit argument a con; I prefer to name my parameters).

It may very well be that the bind operator is all we need. However, I would like to continue exploring this space to be sure.

**Comment by mindeavor** [comment]
@spion For the record, partial application is super easy to add in JavaScript :) I do it all the time:

```js
Function.prototype.papp = function (...args) {
  var fn = this;
  return function () {
    return fn.call(this, ...args, ...arguments);
  }
};

var addFive = add.papp(5);
addFive(7) //=> 11

function add (x,y) { return x + y }
```

This technique lines up quite nicely with the proposed pipeline op:

```js
var newScore = person.score
  |> double
  |> add.papp(7)
  |> validateScore
```

**Comment by barneycarroll** [comment]
You're using `this` for that? :0

**Comment by spion** [comment]
@mindeavor I know, I just think that particular variant of partial application isn't flexible enough because many JS libraries don't pay attention to argument order.

Interestingly enough, the bind operator will help avoid attaching things on the prototype (which can cause all kinds of breakage when properties are enumerated) ;)

```js
import {p, pipe} from 'fn-ops'

var newScore = person.score::
               pipe(double)::
               (add::p(7))::
               pipe(validateScore)
```

Uglier, yes. Does achieve the same thing.

**Comment by mindeavor** [comment]
Your "pipe operator version" of `papp` is a bit of a strawman; I don't think anyone suggested defining or using such a function.

Well the main point of the `|>` operator was to code in a point-free-ish style. If you're going to go as far as those examples, you may as well extend the language:

```js
Object.defineProperty(Object.prototype, 'pipe', {
  enumerable: false,
  value: function (fn, ...args) {
    return fn(this, ...args)
  }
})

var result = "hello there"
  .pipe( replace, ' ', '_' )
  .pipe( x => x + "!" )

function replace (str, pattern, out) {
  return str.replace(pattern, out)
}
```

hmm, why are either of our proposals necessary again?

**Comment by spion** [comment]
As I said, the main point of `bind` is precisely to *avoid* attaching things to the built in prototypes. Its full of pitfalls. For example, node's `Stream` class defines `pipe` which will override `Object.prototype.pipe` behaviour.

**Comment by mindeavor** [comment]
I agree with your (1); using the lambda syntax is just fine IMO.

I know extending built-in prototypes is poor practice, but for the moment I'm re-evaluating whether we need new syntax at all for fluent chaining. For example, wouldn't this accomplish the same as the bind operator's chaining behavior?

```js
Object.defineProperty(Object.prototype, 'bindPipe', {
  enumerable: false,
  value: function (fn, ...args) {
    return fn.apply(this, args)
  }
})

var result = "hello there".bindPipe( replaceSpaces, '_' )

function replaceSpaces (out) {
  return this.replace(' ', out)
}
```

Sure we're extending the prototype here, but if `bindPipe` (or some other name) were standardized, no new syntax would be required, no?

**Comment by RangerMauve** [comment]
@mindeavor Extending native prototypes is just bad practice in all cases where you're trying to define your own chainable syntax. With the bind syntax, or even with the pipeline operator, one could import libraries that support nice chaining APIs without having any opportunity for conflicts.

The argument that `bindPipe` might get standardized is very weak since you're more likely going to come up with a fancy use case that isn't going to be standardized any time soon, or the standardized version is going to end up being in conflict with whatever you thought up initially. Not extending native prototypes is an established best practice, so I don't think it makes sense to be arguing for it or using it in examples to back whatever point you're making.

**Comment by mindeavor** [comment]
> Not extending native prototypes is an established best practice, so I don't think it makes sense to be arguing for it or using it in examples to back whatever point you're making.

That's a little black and white, isn't it? Perhaps I'm being unclear; by standardized, I mean accepted into the ES.next spec. I extend the prototype to emulate such a proposed scenario.

In other words, for argument's sake, I propose `Object.prototype.bindPipe` is accepted into the language, just like how `Array.prototype.find` was accepted into ES6. Would either the `|>` operator or the `::` operator provide any significant gain over this `bindPipe` method?

**Comment by RangerMauve** [comment]
@mindeavor Probably not for that case, but the two added syntaxes would allow for custom chainable functions which potentially wouldn't be standarized either ever or any time soon.

Personally, I prefer just using a higher-order `pipe` function for pipelines, but I could see people's excitement over having that as a language feature.

**Comment by barneycarroll** [comment]
Isn't the most obvious benefit of the bind operator that defining new prototypes becomes redundant? `pipe` can exist as a simple function and be invoked on any entity. In contrast, the example wouldn't work with a String literal, which doesn't inherit from Object.

**Comment by mindeavor** [comment]
> the two added syntaxes would allow for custom chainable functions

Are you referring to custom functions that wouldn't be possible to use with `bindPipe`, but would with a new syntax ? If so, I would like to see them – it *is* the question I'm asking, for argument's sake.

@barneycarroll Actually a string literal was the first example I tried it with. It seems to work on my end..

**Comment by RangerMauve** [comment]
@mindeavor I guess I can concede that it'd be possible with such method defined on all objects, but it's more verbose and unlikely to become a standard since AFAIK defining a new method on `Object.prototype` is a pretty huge breaking change.

**Comment by spion** [comment]
The biggest problem with defining anything new on Object.prototype is the use of objects as dictionaries.

**Comment by barneycarroll** [comment]
@spion FWIW Javascript has given us a multitude of ways of avoiding this problem space in recent years:

* ES5's `Object.create( {{literal object expression}}, null )` allows us to create a keyed object without a prototype
* ES7's `Dict` proposal offers idiomatic sugar for achieving the same
* ES6's `Map` allows for keyed entities with explicit get / set / has access methods that eliminate the problem of confusing keys with properties

**Comment by spion** [comment]
@barneycarroll then are there any other reasons why `__proto__` deprecated in favor of `Object.getPrototypeOf` and `Object.setPrototypeOf` ?

**Comment by barneycarroll** [comment]
AFAIK `__proto__` is an ugly kludge that was never part of the standards track.

**Comment by spion** [comment]
"ugly kludge" doesn't explain the reason, but I looked it up and it seems like one of the reasons is indeed breaking dictionaries: https://esdiscuss.org/topic/standardizing-proto (last message)

**Comment by AppShipIt** [comment]
I haven't finished reading the thread yet (I will!) but quick quandaries:

1. These proposals do appear to compete. `(::)` actually looks more natural for closures (aside from aforementioned arguments) since you just name your unary argument `_` (may as well be `this`) by convention.
2. It seems trivial to write a function today just as cleanly e.g.

  ```js
  const pipe = (x, ...fs) => fs.reduce((y, f) => f(y), x)
  const add = (x, y) => x + y
  const double = x => add(x, x)
  pipe(25, double, _ => add(7, _)) // == 57
  ```

3. I believe your proposal does shed light on more interesting problems. For starters, most of your examples manually curry functions. I've been researching functional libraries and every one reimplements auto-currying slightly differently. Unlike `(|>)`, it's quite non-trivial and more oft implemented. I'm biased however, because your proposal inspired me to undertake that one soon.
4. Your proposal (but not `(::)`) would be trivial if we could implement binary operators:

  ```js
  infixl 9 |>(x, f) {return f(x)}
  // </pseudocode>
  const add = (x, y) => x + y
  const double = x => add(x, x)
  25 |> double |> _ => add(7, _) // == 57
  ```

I raise the issue because you're clearly informed and rallying functional style in JS. I'd just love to see that energy as a community directed toward root issues rather than ancillary concerns.

**Comment by thelambdaparty** [comment]
Demo @ [https://jsbin.com/kujeha/4/edit?html,js,console](https://jsbin.com/kujeha/4/edit?html,js,console)

```javascript
// -------------------------------------------------
// Tests
// -------------------------------------------------

@util class Calculations
{
  sum (x, y)
  {
    return x + y
  }
  
  multiply (x, y)
  {
    return x * y
  }
}

console.log 
  (19
    ::Calculations.sum (1)
    ::Calculations.multiply (5)) // 100

console.log
  (Calculations.sum (19) (1)) // 20

let calcStuff = compose 
  (Calculations.sum (2), Calculations.multiply (20))

console.log 
  (8::calcStuff()) // 200

console.log
  (calcStuff (3)) // 100


// --------------------------------------------------------
// @util
// class decorator that statically defines, 
// auto-curries and `::` enables its functions
// --------------------------------------------------------

// enables a function to be used both with 
// :: and normally (auto curried when normal)
// eg: sum (x, y) => x + y
//     sum (1) (2) == 3
//     (3)::sum (1) == 4
function multiFunction (_function)
{
  // wraps the function and detects
  // if :: is being used. Does this by checking
  // the type of this.constructor, if it's the same
  // as the wrapped function that means :: wasn't 
  // used so it's treaded as a normal function call
  function wrapped (...params)
  {
    if (this.constructor.name == "wrapped")
      return curried.apply (this, params)
    else
      return _function.apply (null, params.concat (this))    
  }  
  // if you're not using :: then the 
  // function will be auto curried
  function curried (...args)
  {
    if (args.length == _function.length)
      return _function.apply (this, args)
    else
      return (...params) => 
        curried.apply (this, [].concat (args, params))
  }
  // this will be the function 
  // defined in the decorated class
  return wrapped
}

// decorator that wraps class functions 
// and turns them static so they can be 
// used without instantiating the class
function util (Class)
{
  Object
    .getOwnPropertyNames (Class.prototype)
    .forEach (property =>
      Class[ property ] = 
        multiFunction (Class.prototype[ property ]))
  
  return Class
}

// simple compose function
function compose (...functions) 
{
  return multiFunction (function (value) 
  { 
    return functions.reduce ((t, fn) => fn (t), value) 
  })
}
```

Pipeline operator is obviously **better**, none of the above `@util` code is needed to achieve the same functionality (except for the currying).

Demo @ [http://bit.ly/1QVIrbx](http://bit.ly/1QVIrbx)
`// hit Compile, then Eval, then check the console (F12)`

```javascript
// -------------------------------------------------
// Tests
// -------------------------------------------------

let Calculations = {
  sum : (x, y) => x + y,
  multiply : (x, y) => x * y
} |> curry;

Number (2)
|> Calculations.sum (3) 
|> Calculations.multiply (5) 
|> console.log // 25


// -------------------------------------------------
// Curry
// -------------------------------------------------

function curry (obj) 
{
  Object.keys (obj).forEach (property => 
  {
    let original = obj[ property ]
    
    obj[ property ] = function curried (...args) 
    {
      if (args.length == original.length)
        return original.apply (this, args)
      else
        return (...params) =>
          curried.apply (this, [].concat (params, args))
    }
  })
  
  return obj
}
```

**Comment by spion** [comment]
Depends on what your goals are. JS doesn't support currying out of the box, so if you take that out of the equation:

https://jsbin.com/xaliyiyaho/1/edit?html,js,console

**Comment by blesh** [comment]
I'm a fan of both proposals, but I think they're orthogonal.

The pipe operator is more about operating with certain types of functions,

The function bind operator is more about extending existing objects and types. In fact, I think the biggest hang up with this one is the desire to have something more like C# extension methods without adding syntax that's too crazy.

The pipe operator is much, much simpler in concept than the function bind operator.

Again, I like both of them though, and I'd love to have both.

**Comment by thelambdaparty** [comment]
@spion True, thin arrow lambdas would be very nice. 

@blesh Yeh, pipeline is much simpler. The reason i found out about the bind operator was searching for something similar to C# extension methods, also in Kotlin there are [Extension Functions](https://kotlinlang.org/docs/reference/extensions.html)

If we had both i would always use pipeline, as it would work very nicely with [lodash](https://github.com/lodash/lodash/) and [lodashFP](https://github.com/lodash/lodash/wiki/FP-Guide) and i don't think i would ever use bind operator.

Bind operator is very good for OOP, Pipeline for Functional...

On the [bind operator proposal](http://wiki.ecmascript.org/doku.php?id=strawman:bind_operator) i see:

- better usability for method extraction + this-binding
- better usability for Function.prototype.call
- don’t have to worry about .bind or .call being shadowed/mutated
- addresses some super use cases without need for implicit lexical binding
- static syntax means no dynamic tests (e.g. for mutation of .bind or .call) ⇒ better performance
- important for code generators that don’t want to be penalized for generating .call

So lots of OOP related tasks. Yeh, bind operator for JavaScript, and for [the current generation](https://youtu.be/PSGEjv3Tqo0?t=806) which is of majority OOP programmers, seems to be more important.

I would be happy with any being implemented, but prefer pipeline for its simplicity.

**Comment by blesh** [comment]
> I think i would never use bind operator.

You'd be surprised. If you want to add a method to a third party class, extension methods are king. The tricky business the TC39 needs to figure out around that is how it will integrate with prototypal inheritance, etc. I think they're looking at changing it quite a bit, but I could be mistaken.

Either way, I _LOVE_ both operators, and I wish I could get them both. I suspect there will be a lot of resistance to either one though. Because they're functional additions to a rather imperative language, and they're not very "C-like" or whatever.

**Comment by thelambdaparty** [comment]
What if everyone focused on implementing Macros instead of all the operators? (which is only planned for ES2017)

Then we wouldn't need to bloat the core and let teams/projects decide on their own operators :smile:

**Comment by blesh** [comment]
@thelambdaparty I'm for that too.

**Comment by AlexGalays** [comment]
I loathe prototypes, class, this, bind (and yes, I now precisely how they work), so to me, `|>` is much better than `::`.

**Comment by littledan** [comment]
The intention of this proposal is to largely subsume the bind operator.
