### ISSUE TITLE
Readme indents change

### ISSUE THREAD

**Issue by FrameMuse** [tc39/proposal-pipeline-operator#239]
There are no indents all around the whole readme, there should be indents, i.e. 2 spaces.
This is a general js tendency, for example here:
```js
context
  .call1()
  .call2()
  .call3()
```

So in the readme it should be:
```js
return xf
  |> bind(^['@@transducer/step'], ^)
  |> obj[methodName](^, ACC)
  |> xf['@@transducer/result'](^);
```

This is not critical but default js formaters make indents before the accessors, so I think we should follow it.

**Comment by tabatkins** [comment]
Fixed by #240
