### ISSUE TITLE
Is CoC improperly used in this proposal recently?

### ISSUE THREAD

**Issue by fxladdercme** [tc39/proposal-pipeline-operator#248]
Recently, I frequently observe some Collaborators mentions CoC.

https://github.com/tc39/proposal-pipeline-operator/issues/246#issuecomment-939299842  against me
>Okay, let me be more explicit here. You are willfully misunderstanding our positions and making arguments in bad faith, and continue to do so after being corrected. This violates our CoC principles, and is not a topic that is going to continue in any thread. Do not attempt to raise this again.

https://github.com/tc39/proposal-pipeline-operator/issues/225#issuecomment-934798959 against @SRachamim 
>I'm going to ask you to stop suggesting it; talking about it in this repository is an unproductive waste of time. Further mentions of it will be marked as off-topic (and continuing to file off-topic comments can eventually lead to CoC enforcement, tho I don't anticipate that being an issue here).

https://github.com/tc39/proposal-pipeline-operator/issues/205#issuecomment-918717394 against many Collaborators
>I will continue to close threads that do not meet the minimum guidelines from our CoC to be respectful, friendly, and patient. If necessary, further moderation action may be taken; I pray it doesn't become necessary.

So here is my take.

>willfully misunderstanding our positions and making arguments in bad faith

If you think so, clarify. What exactly do you think you are misunderstood in #246?

>and continue to do so after being corrected. 

It has never been corrected. You did not clarify the misunderstanding.

>This violates our CoC principles, and is not a topic that is going to continue in any thread. Do not attempt to raise this again.

Doesn't make sense because you did not clarify.

>I'm going to ask you to stop suggesting it; talking about it in this repository is an unproductive waste of time. 

- Is this your personal opinion or shared idea among the collaborators/proposal champion members, especially for "in this repository is an unproductive waste of time"?

- If it's a shared idea, why don't you announce this?  then you don't have to waste your time.

**In this repository, a talk including criticism of the proposal is strictly prohibited because it's an unproductive waste of time** 

- How do you define/explain the word "productive" by yourself? If a proposal has a severe defect, is the criticism really an unproductive waste of time to the JavaScript community as a whole?

>This violates our CoC principles, and is not a topic that is going to continue in any thread. Do not attempt to raise this again.

>Further mentions of it will be marked as off-topic (and continuing to file off-topic comments can eventually lead to CoC enforcement, tho I don't anticipate that being an issue here).

>I will continue to close threads that do not meet the minimum guidelines from our CoC to be respectful,

Reading your comments, I don't think you are the faithful advocator of CoC, and I think you simply take advantage of CoC in the very wrong manner.

Okay, let me be more explicit here.

In this repository, do you have the power to decide what the Contributors should talk about or not?
 
Do you abuse your power of moderation? @tabatkins
Do you take advantage of his abuse of power? @js-choi

**Comment by tabatkins** [comment]
The [TC39 CoC](https://tc39.es/code-of-conduct/), which I and @js-choi have previously linked you to, has the recommended escalation mechanisms if you believe anyone is violating our norms of communication. 

Filing an issue in this repository is not one of those, so closing and locking.
