### ISSUE TITLE
In defense of "HOFP"

### ISSUE THREAD

**Issue by fxladdercme** [tc39/proposal-pipeline-operator#249]
This is a spin-off issue of **_In defense of unary functions_ #233**

https://github.com/tc39/proposal-pipeline-operator/issues/233#issuecomment-939137381 @tabatkins 
>Yes, in those very quotes you listed, several of us have explicitly talked about functional programming being a strong and common pattern in JS. Absolutely no one is disputing that; it would be silly to do so. What we've repeatedly and explicitly talked about is _higher-order_ functional programming (functions that take functions to make functions) as a general programming strategy, thus our repeated use of "HOF" or "HOFP" when talking about this subject. HOFP is a minority pattern in JS and will very likely always be, and due to fundamental design choices in JS's syntax and structure, will never be as convenient to use as it is in other languages that were designed with HOFP in mind.
(Both your comment and this reply are off-topic, so I'm marking them as such.)

Please note this is **not a _duplicate_ issue** since the moderator marked as off-topic there saying:
>(Both your comment and this reply are off-topic, so I'm marking them as such.)

**_Why does this proposal try to restrict the JS programmers' latitude "How we should program in JavaScript" ?_ #246**

https://github.com/tc39/proposal-pipeline-operator/issues/246#issuecomment-939299842 @tabatkins 
>Okay, let me be more explicit here. You are willfully misunderstanding our positions and making arguments in bad faith, and continue to do so after being corrected. This violates our CoC principles, and is not a topic that is going to continue in any thread. Do not attempt to raise this again.

For this comment, I made it clear nothing has been **corrected** because he did not clarify the so-called "misunderstanding".
**_Is CoC improperly used in this proposal recently?_ #248**

>Do not attempt to raise this again.

I don't think he has succeeded to justify himself, so here's another issue.

-----

First off, as addressed in **_Why does this proposal try to restrict the JS programmers' latitude "How we should program in JavaScript" ?_ #246**, 

>due to fundamental design choices in JS's syntax and structure, will never be as convenient to use as it is in other languages that were designed with HOFP in mind. 

This is a false statement because https://brendaneich.com/2008/04/popularity/

>I’m not proud, but I’m happy that I chose Scheme-ish first-class functions and Self-ish (albeit singular) prototypes as the main ingredients.

Since then, JavaScript has been a multi-paradigm language that is mostly a hybrid of Java-like ObjectOreintedProgramming and Scheme/Lisp-like FunctionalProgramming.
Brendan Eich, the JavaScript language creator mentions **Scheme-ish first-class functions** that mean essentially "HOFP", 

So JavaScript is not like what they think (as members of the champion team and a few others repeatedly claim here) .

Secondly,

https://github.com/tc39/proposal-pipeline-operator/issues/233#issuecomment-939137381 @tabatkins 
>What we've repeatedly and explicitly talked about is **_higher-order_ functional programming (functions that take functions to make functions) as a general programming strategy**, thus our repeated use of "HOF" or "HOFP" when talking about this subject. HOFP is a minority pattern in JS and will very likely always be, 

https://github.com/tc39/proposal-pipeline-operator/issues/233#issuecomment-933026341 @mAAdhaTTah

>I'll also say upfront that one of the things I'm getting from this, given your use of "HOFP", is that we're kind of addressing a "subset of a subset"; namely, that HOFP itself is a subset of FP in JS more generally, which is itself is one of several approaches to programming in JavaScript one can take, based on the problem being solved & stylistic preferences of the author. 

#243 _Usage and readability on unary functions chain_ comments @ljharb 

>Use them all you like; but unary-function-returning unary functions probably wont see a lot of readability benefits from this proposal. That’s fine, though, because this proposal isn't trying to improve the ergonomics of using HOFs or unary functions.

>I think JavaScript has no inherent concept of a unary function - you can certainly write them, but they're no different from functions that take 0 args or N args. In some languages, all functions are unary functions, but that's not how JavaScript works.
I do think that Math concepts are irrelevant for this proposal, since this is a JavaScript proposal - but "math" is off topic for this issue as well.

I think you should stop using the "HOF"  "HOFP" buzzworld that does not mean much in FP, at all.

### How common "HOF"  "HOFP"  is in JavaScript (majority) and how it's deeply connected to the Pipeline operator (in the mathematical sense)

---

`Array.map` is an endo-functor that is commonly used in JavaScript, in OOP form like this:

```js
const array = [1, 2, 3];
const f = a => a * 2;

console.log(
  array.map(f)
); // [2, 4, 6]
```

I will rewrite this OOP code to FP code with the function application = pipeline operator 

```js
// map : f  =>  (A => A.map(f))
// map : Function => Function
const map =
  f =>
    A =>
      A.map(f);  // or you can define your own map whatever you like

console.log(
  array |> map(f)
); // [2, 4, 6]
```

Remember `map`  in the above code is the identical entity of `Array.map`. Just not in OOP form.

```js
array.map(f)
array |> map(f)
```

 `map` is an endo-functor that is **_higher-order_ function that takes functions to make functions** as the definition in category theory, and it's implemented as the built-in Array object method in JavaScript.

So, with the pipeline operator, we will be able to see the connection between OOP and FP, and what the `map` actually is.
**map : Function => Function**   
HOFP or stop using this buzzword nonsense.

`map` is the higher-order functional programming (functions that take functions to make functions) as a general programming strategy in JavaScript.
If you don't know the fact, it's simply you are too accustomed to using OOP, and the fact is JavaScript is also a Functional language, Hybrid.

Most importantly, as I addressed in **_Why does this proposal try to restrict the JS programmers' latitude "How we should program in JavaScript" ?_ #246** , I think no one should restict the programmers' latitude of their programming style, and I think this is exactly what "Hack pipe" or the champion members are doing right now.

FYI,
[Array.prototype.flatMap()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) is introduced in ES2019
https://github.com/tc39/proposal-flatMap/issues/10 @dtipson
>This proposal essentially gives native Arrays the methods they need to work as **Monads** (without having to extend the prototype).

They add `flatMap` as Monad on top of the `map`  (endo-functor).

```js
array.flatMap(f)
array |> flatMap(f)
```

Pipeline operator is not a  thing to linearize the function chain and with Hack,

```js
array.map(f)
array |> map(f)(#)
```
This thing totally destroys the consistency of the principle.

> I'm getting from this, given your use of "HOFP", is that we're kind of addressing a "subset of a subset"; namely, that HOFP itself is a subset of FP in JS more generally

>when talking about this subject. HOFP is a minority pattern in JS and will very likely always be,

So this is a false statement. JavaScript is not what you think.

**Comment by tabatkins** [comment]
This user has been explicitly told that these comments are off-topic, and continues to repost essentially the same thread. We are pursuing CoC enforcement. Don't engage with them, please.
