### ISSUE TITLE
Real-world examples should show refactored code with temp vars

### ISSUE THREAD

**Issue by vjpr** [tc39/proposal-pipeline-operator#253]
See: https://github.com/tc39/proposal-pipeline-operator#real-world-examples

If the code is being refactored to use the pipe operator, an alternative is for the code to be refactored using temp vars.

IMO, using temp vars and naming intermediate results makes *every* example more readable than pipes, and pipes sometimes retracts from readability. When I see a `%`, I have to look at the previous function and guess what it is returning.

For every example, there is a lot of mental load to figure out what is going on. If this new syntax is introduced, people will use it instead of using temporary variables that would greatly improve readability.

**Pipes will reduce and make it more difficult to name intermediate values making code harder to read**

So it's not a fair comparison to not show non-refactored real-world examples.

```js
// orig
var minLoc = Object.keys( grunt.config( "uglify.all.files" ) )[ 0 ];

// refactored
const files = grunt.config("uglify.all.files")
const minLoc = Object.keys(files)[0];

// With pipes
var minLoc = grunt.config('uglify.all.files') |> Object.keys(%)[0];
```

```js
// orig
const json = await npmFetch.json(npa(pkgs[0]).escapedName, opts);

// refactored
const firstPkg = pkgs[0]
const {escapedName} = npa(firstPkg)
const json = await npmFetch.json(escapedName, opts);

// With pipes
const json = pkgs[0] |> npa(%).escapedName |> await npmFetch.json(%, opts);
```

```js
// orig
return xf['@@transducer/result'](obj[methodName](bind(xf['@@transducer/step'], xf), acc));

// refactored
const boundStep = bind(xf['@@transducer/step'], xf)
const fn = obj[methodName](boundStep)
const xf['@@transducer/result'](fn)

// With pipes
return xf
  |> bind(%['@@transducer/step'], %)
  |> obj[methodName](%, acc)
  |> xf['@@transducer/result'](%);
```

```js
// orig
return this.set('Link', link + Object.keys(links).map(function(rel){
  return '<' + links[rel] + '>; rel="' + rel + '"';
}).join(', '));

// refactored
const links = Object.keys(links).map((rel) => {
  return '<' + links[rel] + '>; rel="' + rel + '"';
});
return this.set('Link', link + links.join(', '))

// With pipes
return links
  |> Object.keys(%).map(function (rel) {
    return '<' + links[rel] + '>; rel="' + rel + '"';
  })
  |> link + %.join(', ')
  |> this.set('Link', %);
```

```js
// Status quo
console.log(
  chalk.dim(
    `$ ${Object.keys(envars)
      .map(envar => `${envar}=${envars[envar]}`)
      .join(' ')}`,
    'node',
    args.join(' ')
  )
);

// refactored
const envvars = Object.keys(envars)
  .map(envar => `${envar}=${envars[envar]}`)
  .join(' ')}
const str = `$ ${envvars}`
const val = chalk.dim(str,  'node', args.join(' '))
console.log(val);

// With pipes
Object.keys(envars)
  .map(envar => `${envar}=${envars[envar]}`)
  .join(' ')
  |> `$ ${%}`
  |> chalk.dim(%, 'node', args.join(' '))
  |> console.log(%);
```

**Comment by js-choi** [comment]
Thanks for opening the issue, as well as #254.

However, I don’t think comparing pipe code with *both* original code *and* temp-variable code is appropriate in the [real-world examples section](https://github.com/tc39/proposal-pipeline-operator/blob/main/README.md#real-world-examples). The point of the real-world examples section is to compare this proposal with status-quo code. A big point is that the [examples’ original writers *could* have written their code with more temp variables but *already* chose not to, instead opting for deeply nested expressions, presumably for brevity](https://github.com/tc39/proposal-pipeline-operator/blob/main/README.md#temporary-variables-are-often-tedious).

In addition, there’s already a comparison with temp-var approaches in the [“Why a pipe operator” section](https://github.com/tc39/proposal-pipeline-operator/blob/main/README.md#temporary-variables-are-often-tedious).

I appreciate the time you took in helping out!
