### ISSUE TITLE
Polyfill with Lodash/Underscore

### ISSUE THREAD

**Issue by AdamBrodzinski** [tc39/proposal-pipeline-operator#26]
I've been using a modified version of `thru` with underscore/lodash chaining to use this in production. I've been planning on making a separate Babel plugin (https://github.com/AdamBrodzinski/pipes-js) but would love to collaborate if you're planning on making one instead. 

I really don't have time to extract this but I have it running on a sideproject, RedScript an Elixir like lang that compiles to JS. 
https://github.com/AdamBrodzinski/RedScript

Essentially you just need to do a bit of regex work to replace the pipes into this:

``` javascript
var res = '555 121-7878'
  |> stripChars '.'
  |> stripChars ' '
  |> stripChars('-')
```

``` javascript
// str - string to change
// char - the character to strip out
// returns transformed string
function stripChars(str, char) {
   return str.replace(char, ' ');
}

var res = _.chain('555 121-7878')
  .pipesCall(stripChars, '.')
  .pipesCall(stripChars, ' ')
  .pipesCall(stripChars, '-').value();

console.log(res);
```

The ES6 version of `pipesCall` is:

```
function pipesCall(firstParam, func, ...restParams) {
  return func(firstParam, ...restParams);
}
```

I also tried to get lo-dash to add this but he wasn't interested.

**Comment by RangerMauve** [comment]
What's the second argument to `pipesCall`? I don't think that adding a dependency as large as lodash or underscore just to have piping via babel makes sense.

**Comment by AdamBrodzinski** [comment]
> What's the second argument to pipesCall?

The second arg is the function to be called, `stripChars` in my example. The signature is a bit weird but lodash expects the first argument to be the param being passed down the chain, and 2nd argument is the function to chain, and then the rest can be whatever is needed.

> I don't think that adding a dependency as large as lodash or underscore just to have piping via babel makes sense.

I agree, using the entire lib for a transform is too heavy. However, you could also import just the chain method from lodash with a custom build. [This version](https://github.com/jameswomack/lochain/blob/master/index.js) was only 60 lines.

Actually after posting this I noticed @mindeavor has a fork of Babel with some mods to it so perhaps he already has a working version?

Also I don't think lodash is the end solution but it would be a nice way to test it out. I've been using a renamed version of `pipesCall` in my production app and it's been working great.

**Comment by RangerMauve** [comment]
@AdamBrodzinski 
> The second arg is the function to be called

I was a little confused because your code specifically says `.pipesCall(stripChars, '.')` where `stripChars` is passed as the first argument and `'.'` passed as the second argument. AFAIK, the pipe operator only works with function that take one argument, and it looks like you're using the second argument in `pipesCall` as some form of partial function application.

Also, it seems that progress on the Babel plugin is being tracked in #18

**Comment by AdamBrodzinski** [comment]
@RangerMauve ah, yea so lodash only passes one argument (the returned value) to the next function. It has the same functionality as [thru](https://lodash.com/docs#thru) but the caller can receive more arguments than just the value in the chain. This makes it behave like Elm/Elixir/etc.. pipes. I've also edited the code to include the code body so that it's more clear what it's returning.

**Comment by RangerMauve** [comment]
@AdamBrodzinski I don't think that this proposal contains the functionality you're describing with the additional arguments, is what I'm getting at. :P

**Comment by AdamBrodzinski** [comment]
@RangerMauve Ah, yea you're right. I didn't look close enough at the multiple param example. If you would write the `format` function in the validation example in the signature for Erlang, Elixir, Elm, and my implementation it would be:

```
function format (obj, prop, regex) {
  if (! regex.test(obj[prop]) ) throw Error('invalid format');
  return obj;
}
```

Also just noticed I forgot the `return` on my example of pipesCall (added)... this is what returns the value back to the chain.

However, this proposal id different and requires returning another function so it doesn't really matter :smile:  Oh well, it looks like i'm going to have to switch to Elm to get my Elixir like pipes :laughing:

**Comment by littledan** [comment]
Interesting to hear; another way you can polyfill is by using a new version of Babel.
