### ISSUE TITLE
The Polyfill

### ISSUE THREAD

**Issue by thomas-jeepe** [tc39/proposal-pipeline-operator#27]
I made a simple pipe func, it returns a function, but can be adjusted to be executed instantly.

``` javascript
let pipe = (...funcs) => (...args) => funcs.slice(1,funcs.length).reduce((v, f) => f(v), funcs[0](...args))
```

Tested [here](https://github.com/thomas-jeepe/minimal-f/blob/master/test/pipe.spec.js)

**Comment by AppShipIt** [comment]
@thomas-jeepe Simpler `const pipe = (x, ...fs) => fs.reduce((y, f) => f(y), x)`

**Comment by notoriousb1t** [comment]
Maybe this would perform better

    function pipe(x) {
      var c = x;
      for (var y = 1; y < arguments.length; y++) {
        c = arguments[y](c, arguments[y]);
      }
      return c;
    }

**Comment by AppShipIt** [comment]
Worth testing but JS engines are pretty intelligent about optimization. That looks harder to optimize because `reduce` is entirely C whereas everything about your loop must be (and is) optimized away (such as the chunk of memory allocated for each `c` or lookup into the arguments object).

**Comment by notoriousb1t** [comment]
Iterating over 1..* arguments is  single pass operation.  It should spank the pants off anything that needs to construct a new array to function.  Regardless, reduce won't be available in older versions of browsers.

**Comment by thomas-jeepe** [comment]
I'll make an old browser friendly and jsperfed thing in a bit.

**Comment by thomas-jeepe** [comment]
This seems to be the fastest on modern chrome(2x faster than a regular for loop), firefox (40x) and safari is well rounded with this one coming out barely on top.

```javascript
function pipeArgumentsVar (arg) {
  var clonedArg = arg;
  var length = arguments.length;
  var func;
  for (var i = 1; i < length; i++) {
    func = arguments[i]
    clonedArg = func(clonedArg, func);
  }
  return clonedArg;
}
```

http://jsperf.com/pipe

**Comment by notoriousb1t** [comment]
That looks great!  I'm pretty sure there is little or nothing to optimize at this point.

**Comment by RangerMauve** [comment]
Are you sure it wouldn't make more sense to just turn stuff like `1 |> f |> g` into `g(f(1))` as part of the transpiler?

**Comment by tycho01** [comment]
Related: there has been a pipeline operator [sweet.js macro](https://gist.github.com/aaronpowell/d5ffaf78666f2b8fb033). Apparently they're [still working on](https://github.com/mozilla/sweet.js/pull/485) getting sweet.js and babel to play nice though. `:(`

**Comment by dallonf** [comment]
Quick little plug: I just published a standalone package along these lines. 

https://github.com/phunware/pipeline

It uses the `reduce` form currently, I didn't have the time to do a thorough investigation of the most performant option, but I'd happily take a PR!

**Comment by tycho01** [comment]
Hah, this reminds me a bit of Lodash's `_.flow` method.

**Comment by dallonf** [comment]
`_.flow` (and several other libs) are _very, very_ close to this... and I really didn't want to make my own... but they don't really get the full benefit of the pipeline operator, in my opinion, because they read like `_.flow(function2, function3)(value1)` (whereas the ideal solution is ` value1 |> function2 |> function3` or the javascript-of-today version of `pipeline(value1, function2, function3)`.

**Comment by tycho01** [comment]
Guess an alternative (ES6) could be like `let pipe = (v, ...fns) => _.flow(...fns)(v)`, but yeah, dependencies would suck for a library.
I kinda see where they were coming from plugging the value in last though, considering composability (also see `lodash/fp`). But yeah, having to read back and forth definitely sucks. :P
I might consider adding this to a global lodash instance with `_.mixin`...

**Comment by littledan** [comment]
Interesting examples.
