### ISSUE TITLE
What if? Use `->` instead `|>`

### ISSUE THREAD

**Issue by miko-github** [tc39/proposal-pipeline-operator#281]
The `->` is more readable than `|>` , Huh?

**Comment by tabatkins** [comment]
`->` is very close to the `=>` of arrow functions (and has been suggested for variations on arrow functions), so it should probably be ruled out.

Also note that several coding-specialized fonts have a special ligature for `|>` to make it look nicer. For example, this is the rendering I got from your message in Gmail:

![image](https://user-images.githubusercontent.com/682840/188987321-2ed99bce-fc21-46cf-a375-bcac0ffbd80d.png)

(It's rendering with FiraCode, which is set as my default monospace font. I don't remember if I did this manually or not.)

**Comment by VitorLuizC** [comment]
Most languages use `|>`, so it's a convention, and it would be awkward to use a different token.

- [F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/#pipelines)
- [Hack](https://docs.hhvm.com/hack/expressions-and-operators/pipe)
- [Julia](https://docs.julialang.org/en/v1/manual/functions/#Function-composition-and-piping)
- [Elixir](https://elixirschool.com/pt/lessons/basics/pipe_operator)
- [Elm](https://dennisreimann.de/articles/elm-functions.html)

**Comment by ljharb** [comment]
Also, due to Coffeescript, `->` means "thin arrow function", so I think this syntax is a nonstarter.
