### ISSUE TITLE
Solution - Two operators?

### ISSUE THREAD

**Issue by bryanrideshark** [tc39/proposal-pipeline-operator#282]
Just throwing this out there, but why can't we do both Hack and F# syntax, just with two different operators?

We already have precedent for this with functions - We have normal functions and arrow functions, we have `call` and `apply`... Surely there's enough room to make two pipeline operators that work as needed based on the code you're handling.

Couldn't we have `|>` for the hack operator, and `|>>` for the F# operator (or some other derivation)? We might argue that the placeholder symbol would then take on different meanings based on which operator you used; but this is already the case with functions and `this`. I think if people prefer one style over the other, they will likely stick to their favorite style, and not encounter much resistance in their day to day work.

We'll still be fighting about which flavor gets to use `|>`, but if there was a way to use an alternative one, it would make sense, and maybe make it possible for libraries like Rxjs to be able to use this syntax.

**Comment by tabatkins** [comment]
This has been suggested a few times in various forms, probably most recently and notably in #237.

The short answer is "probably not". The "F#-style" operator has already affirmatively failed to reach consensus in TC39, with several blockers, and the current proposal is explicitly an attempt to solve those issues. It's also the case that, while JS *is* a multi-paradigm language that's not overly concerned with there being more than one way to do something, it doesn't generally like there being two *extremely similar* ways to do the same thing.

That's not to say that it's *impossible* for an F#-style pipeline to exist in some separate syntax in the future, but we won't be pursuing it as part of *this* proposal.
