### ISSUE TITLE
Raku-style pipelining with less verbose lambda syntax

### ISSUE THREAD

**Issue by Keyacom** [tc39/proposal-pipeline-operator#283]
I know it would be best to talk about this in a separate proposal, but I want to talk about it here because it could affect the status of this proposal, and could result in a move away from Hack-style pipelining.

The proposed `%` variable, which is not yet final, can be there because the pseudo-argument must be something that is neither a prefix or a postfix operator.

I like Raku's syntax for defining non-verbose lambdas with `*` as the arguments (it does not need to be unary, but can lead to unexpected `undefined` results while pipelining).

Some examples of such a syntax:

```raku
my $fun = * + 2; # unary function
say $fun(4); # expected output: 6

$fun = (* + 2) / *; # binary function
say $fun(7, 3); # expected output: 3
```

As for pipelining, Raku uses the `andthen` operator, which requires an expression, or a function, which needs to have a name prefixed with `.`.

```raku
my $fun = * + 2;
say 2 andthen .$fun; # expected output: 4

my $str = 'Maya';
$str ~~ /May/ andthen say "$_ is my birth month"; # expected output: May is my birth month
#`{
  Note: in the above example, the $/ variable could 
  have been referenced too, leading to the same output
}
```

In JavaScript, it could just be less verbose while still using the F# style of pipelining.

NOTE: This is more about introducing a new syntax for lambdas that could be less verbose. Like I said, it would be better to talk about this in a separate proposal.

**Comment by tabatkins** [comment]
Defining lambdas (with any syntax) runs into exactly the same issues that Partial Function Application had; see #221.

But yeah, in general this is indeed a separate proposal and not part of this repo. ^_^
