### ISSUE TITLE
Should this even exist?

### ISSUE THREAD

**Issue by hr8** [tc39/proposal-pipeline-operator#286]
Prompted by another thread, I am posting this as a place for people who might respectfully disagree with the idea of implementing this idea.

**Comment by hr8** [comment]
https://github.com/tc39/proposal-pipeline-operator/issues/285

**Comment by ctcpip** [comment]
@hr8 please refrain from needlessly spamming issues

**Comment by ljharb** [comment]
There are a lot of older threads for that, and given that it has stage 2, the committee has decided "yes, it should exist", and this isn't the proper place to discuss it further.
