### ISSUE TITLE
Pipelines with no left-hand argument? (error or composition without immediate invocation)

### ISSUE THREAD

**Issue by kwijibo** [tc39/proposal-pipeline-operator#29]
What should happen if an argument to the pipeline is not provided at the left-hand side of the expression?
eg:

``` javascript
w = |> x |> y |> z
```

Does it produce a syntax error, or a functional composition?
The latter could be useful in some situations, eg:

``` javascript
result = x.map( |> y |> z )
```

``` javascript
.catch(|>logToFile |> retry(fetchFunc, --numOfAttempts))
```

Of course it's not very verbose to create a composition with an arrow function:
rather than

```
result = x.map( i => i |> y |> z)
```

But this would allow us to do away with a little boiler plate in the same way that _Ghost Methods_ #13 would.

**Comment by kwijibo** [comment]
Another case to consider is, invoking pipelines that start with a function that doesn't take an argument.
Presumably you could do this:
```javascript
result = '' |> x |> y |> z 
```
or
```javascript
result = undefined |> x |> y |> z 
```
or some such?

**Comment by barneycarroll** [comment]
The more this proposal is discussed, the more it seems to me that what people are *really* after is first class curry by default in Javascript ;)

**Comment by christiantakle** [comment]
I think most have trouble understanding the difference between function application and function composition (left-to-right and right-to-left).

Manual currying isn't too bad in newer versions of Javascript

```js
const
  add  = x => y => x + y

[1,2,3].map(add(1)) \\ => [2,3,4]
```
|> is function application so its not designed for use in a pointfree style. Another important thing is Javascript have variadic arguments. Operators and and inlining of functions makes more sense for binary functions.

Haskell examples
```hs
-- Explanation in Javascript
-- .      -> let compose = (f,g) => x => (f(g(x)))
-- >>>    -> let pipe    = (f,g) => x => (g(f(x)))
-- & = |> -> let applyR  = (x,f) =>      f(x)
-- $ = <| -> let applyL  = (f,x) =>      f(x)

-- I aliases, since the pipe operator is all the rage these days
($) = <|
(&) = |>

-- Pointfree | Tacit programming
f = mult2 . add1            -- `add1` then `mult2`
f = add1 >>> mult2          -- `add1` then `mult2`

-- Pointful
f x = mult2 . add1 <| x     -- `add1` then `mult2`
f x = add1 >>> mult2 <| x   -- `add1` then `mult2`
f x = x |> (add1 >>> mult2) -- `add1` then `mult2`
f x = x |> mult2 . add1     -- `add1` then `mult2`
f x = x |> add1 |> mult2    -- `add1` then `mult2`
```

I hope this shows that the syntax is a minor thing aslong one understand the underlying principle. Then you can write your program in a way that makes sense for the domain.

Would the argument name help documenting the code?
Yes: Use function application
No:  Use function composition

Choose the reading direction that makes the most sense.

I don't think javascript would gain much from just the |> operator. We can allready do the same things in a concise mannor. If we start being able to inline functions or define our own operators then whats the point? Use another language that supports it that compliles to JS such as:

* LiveScript  (to Javascript, http://livescript.net/)
* ghcjs,      (Haskell, https://github.com/ghcjs/ghcjs)
* websharper  (F#, http://websharper.com/)
* js_of_ocaml (ocaml, http://ocsigen.org/js_of_ocaml/)
* ... and many others.

Aside:
My intuition of application is giving small machines input, take the result and put into another machine.

With composition I first build a big machine and then feed it the input.

**Comment by littledan** [comment]
Let's leave this for a follow-on proposal.
