### ISSUE TITLE
Consistent Piping Behavior

### ISSUE THREAD

**Issue by lukeed** [tc39/proposal-pipeline-operator#44]
Coming from an Elixir, I would expect this operator to ***always*** "pipe" the previous function's return value to the current function's first parameter.

In fact, it's more consistent this way, even within the examples provided. 

For example, all the pipes to `double` are _already_ assuming that the previous value is `double`'s first/only param. This assumption is the case for all (currently proposed) single-param functions. It should, naturally, extend to functions of all parity.

The pipe operator is excellent and (I assume) designed for functional programming. If the cost of using it is "repetitive" parameters, then that's a fantastic price to pay!

```js
function doubleSay (str) {
  return str + ", " + str;
}
function capitalize (str) {
  return str[0].toUpperCase() + str.substring(1);
}
function exclaim (str) {
  return str + '!';
}

let result = "hello"
  |> doubleSay // assumed 1st
  |> capitalize // assumed 1st
  |> exclaim; // assumed 1st
```
> Single parity: Expected, nice, consistent

#### Current Validation example:

```js
function bounded (prop, min, max) {
  return function (obj) {
    if ( obj[prop] < min || obj[prop] > max ) throw Error('out of bounds');
    return obj;
  };
}
function format (prop, regex) {
  return function (obj) {
    if ( ! regex.test(obj[prop]) ) throw Error('invalid format');
    return obj;
  };
}

function createPerson (attrs) {
  attrs
    |> bounded('age', 1, 100)
    |> format('name', /^[a-z]$/i)
    |> Person.insertIntoDatabase;
}
```

> Instantiating new functions per call
> Auto-pass to first param is gone
> Different behavior entirely from single-parities

#### Proposed Alternative

```js
function bounded (obj, prop, min, max) {
  if ( obj[prop] < min || obj[prop] > max ) throw Error('out of bounds');
  return obj;
}
function format (obj, prop, regex) {
  if ( ! regex.test(obj[prop]) ) throw Error('invalid format');
  return obj;
}

function createPerson (attrs) {
  attrs
    |> bounded('age', 1, 100)
    |> format('name', /^[a-z]$/i)
    |> Person.insertIntoDatabase;
}
```

> Function mutators instantiated **only once**
> Consistent behavior across all parity
> Usage remains the same

I can provide more examples if needed, or try to explain myself further if I did a poor job. Just let me know.

Thanks!

**Comment by gilbert** [comment]
This has been thoroughly debated here: https://github.com/gilbert/es-pipeline-operator/issues/4

**Comment by jamen** [comment]
I was part of the opposition in #4 it looks like, and I don't really remember my arguments against it...  

Since then, I have used Elixir, and I **really** like that behavior.  So I am for it too.

**Comment by lukeed** [comment]
I missed that at time of posting, sorry.

I will say, that once you get used to the elixir behavior (as described here) it's impossible to leave. Some even say it's the best feature of elixir ;-)

**Comment by lukeed** [comment]
My main gripe here, aside from the convenience, is that the currently proposed syntax creates new functions per call, which can't be inline cached, which is gunna be detrimental for performance. Will never use for this reason alone, despite my love for an elixir(-like) pipe.

**Comment by lukeed** [comment]
@gilbert I don't meant the arrows. I mean the multi-param functions that return other functions.

For example, the `Validation` example I copied above. In it, `bounded` and `format` accept props initially but return a new function of `obj` in order to allow chaining.

**Comment by satya164** [comment]
@lukeed since JavaScript doesn't have automatic currying by default, changing the function call syntax to not behave like normal function calls is confusing imo. it feels completely alien to someone with JS background.

**Comment by lukeed** [comment]
@satya Not to me =) I'm primarily a JS developer (for years now); I just have also used Elixir.

Plus, it's about adding a new feature, might as well actually add something new, even if it includes currying for first time imo.

**Comment by gilbert** [comment]
> I mean the multi-param functions that return other functions.

The technical name for this is **currying**; this is the term you use when you define your function to return other functions for additional arguments. For example:

```js
var f = (x) => (y) => x + y
```

This is a curried function. Many programmers already curry their functions for convenience. For example, a callback-friendly log function:

```js
var log = (message) => (x) => { console.log(message,x); return x }

fetch('/stuff').then( log('Got stuff:') ).then(...)
```

If you have a curried function, then you will always create a new function on first invocation, independent of the pipeline operator (the current proposal just happens to fit conveniently). If you don't have a curried function, you can use an arrow, which will compile into code that ends up **not** creating a function anyway.

With this in mind, could you clarify what you mean by "if it includes currying for first time" @lukeed?

**Comment by lukeed** [comment]
Right, sorry. I meant automatic currying -- wrote that while still in bed 😴 

I still stand by my preference for an head-first behavior -- what we're calling the Elixir style. It pairs _really_ nicely with the `papp` proposal, which would be tail-first, its opposite.

```js
const add = (x,y) => x + y;
const sub = (x,y) => x - y;

// default, head-first
24 |> add(23) |> sub(5)
//=>sub( add(24,23), 5 )
//=> 42

// papp, tail-first
24 |> add.papp(23) |> sub.papp(5)
//=> sub( 5, add(23,24) )
//=> -42
```

Really easy to read. Data flows one directionally by default, instead of mind-melding about what & where each functional step is receiving or returning. Can't get simpler IMO

**Comment by TehShrike** [comment]
If auto-currying is added to JS, it should be made available to all functions, not just ones in expressions whose return values are being composed using this unrelated feature.

Auto-currying is difficult to add to JS in this case for the same reason it is in every other case - how do you deal with default argument values or spread arguments?

I love currying, but this proposal isn't the place to add it.

**Comment by lukeed** [comment]
I disagree. It doesn't need to make its way & affect everything. As it is, you can already `.bind` functions with arguments and curry in that sense. TBH, I don't care about that.

Piping is all about data flow... passing output from one function to another. It should be a uniform, consistent pass, and not affect any non-piped functions.

A pipe, is essentially an `arguments.unshift(newArg)`. A papp is an `arguments.push(newArg)`... essentially.

**Comment by gilbert** [comment]
The latter half of your example is incorrect. This would be the behavior:

```

**Comment by gilbert** [comment]
@lukeed The latter half of your example is incorrect. This would be the behavior:

```js
// papp, tail-first
24 |> add.papp(23)
//=> add.papp(24,23)
//=> <function>

24 |> add.papp(23) |> sub.papp(5)
//=> sub.papp( add.papp(24,23), 5 )
//=> <function>
```

I encourage you to read through #4 and respond to the problems outlined in the discussion directly.

**Comment by satya164** [comment]
@lukeed

> even if it includes currying for first time

It's not about adding currying for the first time. You can do currying in JS already. It's not about adding a feature for auto-currying to the language either.

The problem with this proposal is it uses the same syntax as a function call `add(a)`, but changes it's meaning to add auto-currying. Which will cause unnecessary confusion. If the same syntax does auto-currying here, it should do that everywhere else.

**Comment by lukeed** [comment]
Okay, I'll reread #4 more carefully later tonight!

In the meantime, this is what I was picturing the pipe operator would be translated into:

```js
const add = (x,y,z) => x + y + z;
const sub = (a,b) => a - b;

const pipe = (fn, x) => function () {
  Array.prototype.unshift.call(arguments, x);
  return fn.apply(fn, arguments);
}

// 2 |> add(3,4)
pipe(add, 2)(3, 4)
//=> 9

// 2 |> add(3,4) |> sub(6)
pipe(sub, pipe(add, 2)(3, 4))(6)
//=> 3
```

Also, Thanks for your time~! I'm sad I didn't come across this proposal earlier.

**Comment by rbuckton** [comment]
Please also consider https://github.com/rbuckton/proposal-partial-application as well.

With both proposals you could write this as:
```js
function createPerson (attrs) {   
  attrs
    |> bounded(?, 'age', 1, 100)
    |> format(?, 'name', /^[a-z]$/i)
    |> Person.insertIntoDatabase(?); 
}
```

**Comment by littledan** [comment]
The current plan is to not take this suggestion. If partial application is unable to proceed further, we can reconsider it and reopen this issue or #4.
