### ISSUE TITLE
What is the best way to support?

### ISSUE THREAD

**Issue by freMea** [tc39/proposal-pipeline-operator#48]
Hi,

As average js users, what could we push and support this feature so it could be implemented in a next ES version?

**Comment by tomByrer** [comment]
Use it in projects?
https://github.com/SuperPaintman/babel-plugin-syntax-pipeline

**Comment by willin** [comment]
checkout: https://github.com/AirDwing/esnext-pipeline-biolerplate

**Comment by MeirionHughes** [comment]
you say that, but the bind proposal has been in babel for like 2 years and its no-where to be seen. ;(

**Comment by willin** [comment]
@MeirionHughes already support checkout the project i just push

**Comment by MeirionHughes** [comment]
I was replying to Tom. Not to be pedantic, but babel support !== esnext, as I mentioned, the [bind operator](https://github.com/tc39/proposal-bind-operator) is also supported by babel, actively used in projects, and has been for a few years. But the proposal is no-where near getting into the next es version as far as I can see. :(

**Comment by littledan** [comment]
I put it on the agenda last meeting, but we ran out of time. it's back on the agenda for the next meeting.

**Comment by littledan** [comment]
If you have more feedback about the draft spec I wrote up, that could be very helpful. See https://github.com/tc39/proposal-pipeline-operator/issues/52 .

**Comment by Ebuall** [comment]
Is it possible to use/implement in typescript?

**Comment by littledan** [comment]
@Ebuall Those are two very different questions. For use, I don't think it's available. To implement, if I were maintaining TypeScript, I'd be a bit skeptical of this proposal as it hasn't been presented to TC39 yet. cc @DanielRosenwasser

**Comment by Ebuall** [comment]
@littledan I mean something like babel plugin + vscode extension

**Comment by littledan** [comment]
@Ebuall I don't know about the world of vscode extensions, but there's a Babel plugin at https://github.com/SuperPaintman/babel-plugin-transform-pipeline . It doesn't implement this exact spec, though.

**Comment by madnight** [comment]
"Use it in projects?" Actually i do so  https://github.com/madnight/githut i use the `|` syntax but that should be the same as `|>` as far as i understand.

[Example:]( https://github.com/madnight/githut/blob/1faa9764f60516182808c1e938ac1cd464b96bea/src/js/components/LangChart.js#L77)
```js
createSeries(data) {
        const nonLang = new NonLangStore().getConfig()
        return data
            | reject(o => includes(o.name)(nonLang.lang))
            | take(10)
            | map(d => ({
                name: d.name,
                data: map('count')(filter({'name': d.name})(data))
            }))
            | uniqBy('name')
            | sortBy('name')
    }
```

I use this syntax for function chaining now for over one year in this project and from my experience i never had any issues with it. Its way easier (and more fun) to use than other compose methods and i think it should be part of the offical javascript syntax. So i can recommend you to give it a try if you haven't already.

**Comment by egeozcan** [comment]
@madnight that looks awesome.

I was a bit cautious and didn't want to use syntax which may look alien to newcomers so I developed https://github.com/egeozcan/ppipe . I wish I could get rid of the parentheses, and I have an experiment here: https://github.com/egeozcan/pppipe (yes there is an extra p :) ) and without that eval hack, that would have been awesome.

I would be very glad if anyone shared some thoughts.

**Comment by tabatkins** [comment]
Closing this issue, as the proposal has advanced to stage 2 with Hack-style syntax.
