### ISSUE TITLE
Add links to other proposals

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/proposal-pipeline-operator#67]
(Continuation/successor to #64, that's a little more actionable.)

Could you link a few other function composition proposals, to show a few other ways it could be done? Here's a few:

- Operator-based: [this repo](https://github.com/isiahmeadows/function-composition-proposal)
- Function-based: [this comment](https://github.com/fantasyland/ECMAScript-proposals/issues/1#issuecomment-306243513)
- Method-based: [this repo](https://github.com/simonstaton/Function.prototype.compose-TC39-Proposal)

(Shameless plug: mine is the operator variant. I'll also point out that [my proposal also has an alternative for `await` that's more general](https://github.com/isiahmeadows/function-composition-proposal#possible-expansions), but that's a separate issue.)

**Comment by littledan** [comment]
Feel free to make a PR.
