### ISSUE TITLE
Update readme with link to wiki’s four proposals

### ISSUE THREAD

**Issue by js-choi** [tc39/proposal-pipeline-operator#98]
@gilbert’s [splitting of this proposal into four competing proposals in the wiki](../wiki) on 2018-01-31 was an important clarifying moment. But many newcomers to this repository will look at the readme and not realize the discussions that are currently going on.

The readme should be updated with a note linking to the wiki homepage and saying something like:

> The details of the pipeline syntax are currently unsettled. There are [four competing proposals](https://github.com/tc39/proposal-pipeline-operator/wiki) that are being considered. Work is currently underway, for all four plugins, to [formally specify and implement Babel plugins](https://github.com/tc39/proposal-pipeline-operator/issues/89#issuecomment-363853394) before the four proposals will be presented to TC39 again. This readme’s examples show [Proposal 1: F-sharp Style Only](https://github.com/tc39/proposal-pipeline-operator/wiki#proposal-1-f-sharp-style-only). See [recent GitHub issues](https://github.com/tc39/proposal-pipeline-operator/issues?utf8=✓&q=is%3Aissue+sort%3Aupdated-desc+) for more information.

This should quickly get newcomers up to date on the current evolving situation. I could do a pull request with that paragraph if its wording seems okay.

**Comment by littledan** [comment]
PRs welcome!
